### ISSUE TITLE
Custom::CognitoUICustomization Fails To Create

### ISSUE THREAD

**Issue by rutabagaman** [emdgroup/cfn-custom-resource#4]
I took the latest master branch code, but when you deploy you get this CloudFront error:

`Template Error: Encountered unsupported function: Fn::Include Supported functions are: [Fn::Base64, Fn::GetAtt, Fn::GetAZs, Fn::ImportValue, Fn::Join, Fn::Split, Fn::FindInMap, Fn::Select, Ref, Fn::Equals, Fn::If, Fn::Not, Condition, Fn::And, Fn::Or, Fn::Contains, Fn::EachMemberEquals, Fn::EachMemberIn, Fn::ValueOf, Fn::ValueOfAll, Fn::RefAll, Fn::Sub, Fn::Cidr]`

I worked around this by inlining the code in lambda.js into the customresource template(see my branch).  I can deploy the CustomResource stack, but when I try and create a Custom::CognitoUICustomization with UserPoolId, ClientId, CSS and ImageFile the create always hangs without completing.

**Comment by rutabagaman** [comment]
The corresponding error: 
`{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'jmespath'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'jmespath'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}`
